services:
  rplace:
    image: rplace:1.2
    container_name: rplace
    hostname: rplace
    restart: unless-stopped
    volumes:
      - ./db:/rplace/back/db
    env_file: .env
    ports:
      - 3080:3000
