services:
  rplace:
    image: rplace:0.1
    container_name: rplace
    hostname: rplace
    restart: unless-stopped
    volumes:
      - ./db:/rplace/back/db
    env_file: .env
    ports:
      - 80:3000
